### ISSUE TITLE
Loading pre-trained model.

### ISSUE THREAD

**Issue by EmreOzkose** [csukuangfj/icefall-asr-conformer-ctc-bpe-500#2]
Hi, when I try to load pretrained model, I got this error:

```
2021-10-19 11:16:48,637 INFO [train.py:647] Training started
2021-10-19 11:16:48,637 INFO [train.py:648] {'exp_dir': PosixPath('conformer_ctc/experiments/conformer_ctc_pretrained_1'), 'lang_dir': PosixPath('data/lang_bpe'), 'feature_dim': 40, 'weight_decay': 1e-06, 'subsampling_factor': 4, 'start_epoch': 0, 'num_epochs': 100, 'best_train_loss': inf, 'best_valid_loss': inf, 'best_train_epoch': -1, 'best_valid_epoch': -1, 'batch_idx_train': 0, 'log_interval': 10, 'reset_interval': 200, 'valid_interval': 3000, 'beam_size': 10, 'reduction': 'sum', 'use_double_scores': True, 'accum_grad': 1, 'att_rate': 0.7, 'attention_dim': 512, 'nhead': 8, 'num_decoder_layers': 6, 'is_espnet_structure': True, 'mmi_loss': True, 'use_feat_batchnorm': True, 'lr_factor': 5, 'warm_step': 80000, 'feature_type': 'fbank', 'world_size': 1, 'master_port': 12354, 'tensorboard': True, 'feature_dir': PosixPath('data/fbank'), 'max_duration': 270, 'bucketing_sampler': False, 'num_buckets': 30, 'concatenate_cuts': True, 'duration_factor': 1.0, 'gap': 1.0, 'on_the_fly_feats': False, 'full_libri': False}
2021-10-19 11:16:49,083 INFO [lexicon.py:96] Loading pre-compiled data/lang_bpe/Linv.pt
2021-10-19 11:16:51,044 INFO [train.py:670] About to create model
model is loaded to device
2021-10-19 11:16:54,171 INFO [train.py:270] Loading checkpoint from path/to/icefall-asr-conformer-ctc-bpe-500/exp/pretrained.pt
Traceback (most recent call last):
  File "conformer_ctc/train.py", line 787, in <module>
    main()
  File "conformer_ctc/train.py", line 780, in main
    run(rank=0, world_size=1, args=args)
  File "conformer_ctc/train.py", line 700, in run
    checkpoint = load_pretrained(pretrained_path, model, optimizer)
  File "conformer_ctc/train.py", line 272, in load_pretrained
    checkpoint = torch.load(filename, map_location="cpu")
  File "path/to/miniconda3/envs/k2s/lib/python3.8/site-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "path/to/miniconda3/envs/k2s/lib/python3.8/site-packages/torch/serialization.py", line 764, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```

In summary, this line give error:
```
checkpoint = torch.load(filename, map_location="cpu")
```

have you ever faced with this issue?

Note: since I started experiments with K2.v1.6, I am still working with this version. 
```
python3 -m k2.version:
Collecting environment information...

k2 version: 1.6
Build type: Release
Git SHA1: 02163b480003dc4a7404cd455c67db7dcd3e6248
Git date: Tue Aug 24 12:15:09 2021
Cuda used to build k2: 10.1
cuDNN used to build k2: 8.0.2
Python version used to build k2: 3.8
OS used to build k2: Ubuntu 18.04.5 LTS
CMake version: 3.21.1
GCC version: 5.5.0
CMAKE_CUDA_FLAGS:  --expt-extended-lambda -gencode arch=compute_35,code=sm_35 --expt-extended-lambda -gencode arch=compute_50,code=sm_50 --expt-extended-lambda -gencode arch=compute_60,code=sm_60 --expt-extended-lambda -gencode arch=compute_61,code=sm_61 --expt-extended-lambda -gencode arch=compute_70,code=sm_70 --expt-extended-lambda -gencode arch=compute_75,code=sm_75 -D_GLIBCXX_USE_CXX11_ABI=0 --compiler-options -Wall --compiler-options -Wno-unknown-pragmas --compiler-options -Wno-strict-overflow
CMAKE_CXX_FLAGS:  -D_GLIBCXX_USE_CXX11_ABI=0 -Wno-strict-overflow
PyTorch version used to build k2: 1.7.1+cu101
PyTorch is using Cuda: 10.1
NVTX enabled: True
With CUDA: True
Disable debug: True
Sync kernels : False
Disable checks: False
```

Tracing back
---
Creating and loading model :
```
logging.info("About to create model")
    model = Conformer(
        num_features=params.feature_dim,
        nhead=params.nhead,
        d_model=params.attention_dim,
        num_classes=num_classes,
        subsampling_factor=params.subsampling_factor,
        num_decoder_layers=params.num_decoder_layers,
        vgg_frontend=False,
        is_espnet_structure=params.is_espnet_structure,
        mmi_loss=params.mmi_loss,
        use_feat_batchnorm=params.use_feat_batchnorm,
    )

    model.to(device)
    print("model is loaded to device")

    if world_size > 1:
        model = DDP(model, device_ids=[rank])

    optimizer = Noam(
        model.parameters(),
        model_size=params.attention_dim,
        factor=params.lr_factor,
        warm_step=params.warm_step,
        weight_decay=params.weight_decay,
    )

    # === Load Pretrained Model === #
    pretrained_path = "path/to/icefall-asr-conformer-ctc-bpe-500/exp/pretrained.pt"
    checkpoint = load_pretrained(pretrained_path, model, optimizer)
    # === * === #
```

load_pretrained():
```
def load_pretrained(
    filename: Path,
    model: nn.Module,
    optimizer: Optional[torch.optim.Optimizer] = None,
    scheduler: Optional[torch.optim.lr_scheduler._LRScheduler] = None,
    scaler = None,
):
    """
    TODO: document it
    """
    logging.info(f"Loading checkpoint from {filename}")
    
    checkpoint = torch.load(filename, map_location="cpu")

    if next(iter(checkpoint["model"])).startswith("module."):
        logging.info("Loading checkpoint saved by DDP")

        dst_state_dict = model.state_dict()
        src_state_dict = checkpoint["model"]
        for key in dst_state_dict.keys():
            src_key = "{}.{}".format("module", key)
            dst_state_dict[key] = src_state_dict.pop(src_key)
        assert len(src_state_dict) == 0
        model.load_state_dict(dst_state_dict, strict=False)
    else:
        model.load_state_dict(checkpoint["model"], strict=False)

    checkpoint.pop("model")

    def load(name, obj):
        s = checkpoint.get(name, None)
        if obj and s:
            obj.load_state_dict(s)
            checkpoint.pop(name)

    load("optimizer", optimizer)
    load("scheduler", scheduler)
    load("grad_scaler", scaler)

    return checkpoint
```

I barrowed load_pretrained() from v1.9, but the problem is 1st major part which is torch.load()

**Comment by csukuangfj** [comment]
Please use `git lfs` to download the model.

```
git lfs install
git clone https://github.com/csukuangfj/icefall-asr-conformer-ctc-bpe-500
```

Remember to run `git lfs install` before `git clone`.

You may also use `git lfs pull` if you did not run `git lfs install`.

**Comment by csukuangfj** [comment]
You can check the file size inside your `exp` and `data` directories. The size should be very small since you have not downloaded them yet.

**Comment by csukuangfj** [comment]
Please see the usage of this repo in icefall
https://github.com/k2-fsa/icefall/blob/d30244e28f474f53a31556d49008bd8ef1278ed3/.github/workflows/run-pretrained.yml#L69

```bash
          sudo apt-get -qq install git-lfs tree sox
          cd egs/librispeech/ASR
          mkdir tmp
          cd tmp
          git lfs install
          git clone https://github.com/csukuangfj/icefall-asr-conformer-ctc-bpe-500
          cd ..
          tree tmp
          soxi tmp/icefall-asr-conformer-ctc-bpe-500/test_wavs/*.flac
          ls -lh tmp/icefall-asr-conformer-ctc-bpe-500/test_wavs/*.flac
```

Pay attention to `git lfs install`

**Comment by EmreOzkose** [comment]
Thank you so much :rocket:
